-- =========================================
-- E-commerce Customer Analysis SQL Queries
-- =========================================


-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT *
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount > (
    SELECT AVG(purchase_amount) FROM customer
);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, AVG(review_rating) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;


-- Q4. Compare the average purchase amounts between Standard and Express Shipping.
SELECT shipping_type, AVG(purchase_amount) AS avg_purchase
FROM customer
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue.
SELECT subscription_status,
       AVG(purchase_amount) AS avg_spend,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       COUNT(*) AS total_orders,
       SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on previous purchases.
SELECT customer_id,
CASE 
    WHEN previous_purchases = 0 THEN 'New'
    WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
    ELSE 'Loyal'
END AS customer_segment
FROM customer;


-- Q8. What are the top 3 most purchased products within each category?
SELECT category, item_purchased, COUNT(*) AS purchase_count
FROM customer
GROUP BY category, item_purchased
ORDER BY category, purchase_count DESC;


-- Q9. Are customers who are repeat buyers (more than 5 purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(*) AS total_customers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group;